feat(migrations): Add events migrations
getsentry/snuba pull request #1103
Opened 2020-07-08 20:16 UTC by lynnagara

Add the migration that creates the events table.

It collapses all of the existing add column statements that
are part of the events migration function since those migrations
should have already been performed in a previous Snuba version.

The operation to create the sentry_dist_ro table should also be part of
this migration, however it needs to be split into a separate storage and
storage set first.

2020-07-08 23:02 UTC, fpacifici requested changes
please fix the sharding key. Otherwise just one clarification on the description

> It collapses all of the existing add column statements that
> are part of the events migration function since those migrations
> should have already been performed in a previous Snuba version.

Do you mean that those statements will not be ported to this framework ? If yes what is the cutover plan for someone (on prem) that has a very old existing sentry_local table from before all those migrations were applied ? If they move to a new version that is fully based on the new migration system they would be missing those migrations. Or do we plan to prevent people from skipping a version that still has old migrations to be applied before they start using the new framework ?

2020-07-09 00:19 UTC, lynnagara commented on snuba/migrations/snuba_migrations/events/0001_events_initial.py
> +                    local_table_name="sentry_local", sharding_key=None
Oops, thanks

2020-07-09 00:32 UTC, fpacifici approved these changes

2020-07-09 00:39 UTC, lynnagara commented
About the cutover plan, I was under the impression that as long as we are in a different release to the last migration in the previous list, we can safely proceed with this since the migrations would be completed. I will double check this though.

2020-07-10 17:21 UTC, merged