fix(query) Query equality functions for tests
getsentry/snuba pull request #1457
Opened 2020-10-30 22:27 UTC by evanh

Add query equality functions to the different query classes. Align the Logical
and Clickhouse query signature with the other query classes. Also do some mypy
cleanup, now that the logical query takes an Entity instead of a TableSource.
This isn't used much right now, but will be very useful for testing SnQL.

2020-11-02 22:57 UTC, fpacifici requested changes
Could you please add the __eq__ method to the clickhouse query as well ?
This way it would be the only query class behaving differently than the others.

2020-11-03 21:50 UTC, evanh commented
The clickhouse query extends the ProcessableQuery class, which already has the equality. Is there another one I'm missing?

2020-11-05 17:58 UTC, fpacifici requested changes
two missing fields to check.

2020-11-05 17:58 UTC, fpacifici commented on snuba/clickhouse/query.py
>  class Query(AbstractQuery[RelationalSource]):
This adds the `prewhere`  attribute. So it needs to overrided the eq method.

2020-11-05 17:58 UTC, fpacifici commented on snuba/query/logical.py
> +            from_clause=from_clause,
this class adds the `final` attribute so it needs to override eq.

2020-11-05 18:24 UTC, fpacifici approved these changes
Did you try to replace this old tech debt with your equality check ?
https://github.com/getsentry/snuba/blob/master/tests/query/parser/test_query.py#L837-L847

2020-11-05 19:59 UTC, evanh commented
> Did you try to replace this old tech debt with your equality check ?
> https://github.com/getsentry/snuba/blob/master/tests/query/parser/test_query.py#L837-L847

Yep, I did. I forgot to delete the old checks though.

2020-11-05 21:40 UTC, merged