Use sentry-sdk for collecting events
getsentry/snuba pull request #162
Opened 2018-08-31 17:25 UTC by alex-hofsteede

2018-08-31 20:51 UTC, tkaemming approved these changes
:parrot:

2018-09-04 18:39 UTC, bretthoerner approved these changes

2018-09-04 18:54 UTC, bretthoerner requested changes

2018-09-04 19:06 UTC, bretthoerner approved these changes
I went ahead and added `git` to Docker to fix the build.

2018-09-04 20:34 UTC, merged