ref(validation): Hard code in ifNull permutations
getsentry/snuba pull request #2083
Opened 2021-09-07 22:50 UTC by MeredithAnya

After adding in some missed functions in https://github.com/getsentry/snuba/pull/2067 there was still one function that was showing up in the datadog metics as not valid: `ifnull`. Datadog metrics tag values are always lowercased so we can't know what the original was, but it wasn't `ifNull` (otherwise it would have been found in `GLOBAL_VALID_FUNCTIONS` set.

In looking at ClickHouse docs, it looks like keywords are case-insensitive https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-keywords (but functions are often case sensitive). 

I tested out `ifnull`, IfNull, IFNULL` locally, and in the code it looks like we can confirm that https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/ifNull.cpp#L92-L95.

2021-09-07 22:57 UTC, vladkluev approved these changes

2021-09-07 22:57 UTC, vladkluev commented on snuba/query/functions.py
> +    # TODO(meredith): certain functions are case insensitive, but an ifNull varient
nit
```suggestion
    # TODO(meredith): certain functions are case insensitive, but an ifNull variant
```

2021-09-07 23:34 UTC, lynnagara requested changes
Can't we just search our codebase and remove the offending function? It's probably this line: https://github.com/getsentry/snuba/blob/master/snuba/subscriptions/data.py#L154

I don't get why we need to hard code all the permutations

2021-09-07 23:42 UTC, MeredithAnya commented
> Can't we just search our codebase and remove the offending function? It's probably this line: https://github.com/getsentry/snuba/blob/master/snuba/subscriptions/data.py#L154
> 
> I don't get why we need to hard code all the permutations

we can do that. I didn't see this, I was looking for the offending function in Sentry instead

2021-09-08 18:12 UTC, nikhars approved these changes
Nit: Could you update the PR title to reflect the newer change you have made? Other than that LGTM.

2021-09-08 18:26 UTC, merged