feat(metric-alerts): Adds subscription consumer for metrics [INGEST-623]
getsentry/snuba pull request #2325
Opened 2021-12-22 08:21 UTC by ahmedetefy

Reverts getsentry/snuba#2314

2021-12-22 20:59 UTC, lynnagara requested changes
I'm not sure I get what the goal of this PR is. Why would we want to support metrics consumers without a commit log even for dev/testing? AFAIK metrics should always have a commit log associated with them so we can run subscriptions.

I think having the option to turn metrics on and off via ENABLE_METRICS_SUBSCRIPTIONS flag is useful but I don't get why we should add the third option of supporting it without a commit log. That seems like it should be a core part of metrics functionality as it is required for subscriptions.

2021-12-22 20:59 UTC, lynnagara commented on snuba/datasets/storages/metrics.py
> +    )
Why would we want to support metrics without a commit log? This is a requirement for subscriptions

2022-01-24 15:55 UTC, evanh commented
@fpacifici Are these changes to the topic OK to ship? @ahmedetefy Can you give some context on why you're having counters and sets use the same commit log?

2022-01-24 16:30 UTC, ahmedetefy commented
> @fpacifici Are these changes to the topic OK to ship? @ahmedetefy Can you give some context on why you're having counters and sets use the same commit log?

@evanh `metrics_sets` consumer is required for users crash rate alerts while `metric_counters` is used for sessions crash rate alerts

2022-01-25 01:38 UTC, fpacifici reviewed
Please double check with @oioki that the commit log topic has been created and ported to Krapfen. As you merge this, the consumer will start producing messages on the commit log, so if the topic is not on the right cluster the consuemr will crash, we will backlog, etc. etc.

2022-01-25 13:24 UTC, oioki commented
> Please double check with @oioki that the commit log topic has been created and ported to Krapfen. As you merge this, the consumer will start producing messages on the commit log, so if the topic is not on the right cluster the consuemr will crash, we will backlog, etc. etc.

I can confirm that new topics are created on the Krapfen cluster:
```
$ kafkactl config use-context krapfen
$ kafkactl list topics -o wide
TOPIC                               PARTITIONS     CONFIGS
__confluent.support.metrics         1              segment.bytes=1073741824,retention.ms=31536000000
__consumer_offsets                  50             compression.type=producer,cleanup.policy=compact,segment.bytes=104857600
ingest-metrics                      64             segment.bytes=1073741824,retention.ms=86400000,max.message.bytes=10000000
metrics-subscription-results        8              segment.bytes=1073741824
scheduled-subscriptions-metrics     16             segment.bytes=1073741824,retention.ms=86400000
snuba-metrics                       64             segment.bytes=1073741824,retention.ms=86400000,max.message.bytes=10000000,message.timestamp.type=LogAppendTime
snuba-metrics-commit-log            1              compression.type=producer,min.insync.replicas=1,cleanup.policy=compact,segment.bytes=104857600,retention.ms=86400000,min.compaction.lag.ms=3600000,segment.ms=3600000
```

2022-01-26 07:24 UTC, fpacifici approved these changes

2022-01-28 18:08 UTC, lynnagara commented on snuba/cli/devserver.py
> +            ]
What's the relationship between these 2 consumers? They are both consuming from the same topic, same consumer group, same commit log topic, same commit log group. Isn't that going to cause issues? Should this be run as a single multistorage consumer instead?

2022-01-28 18:21 UTC, lynnagara approved these changes

2022-01-31 16:39 UTC, merged