feat(errors): Add a new errors_v2 storage option
getsentry/snuba pull request #2349
Opened 2022-01-26 18:20 UTC by nikhars

### Context
We would like to introduce a new storage which would be used to write to the new errors clusters in production.

### Testing
Tested on my local cluster with the new storage pointing to a different cluster and changing errors consumer to be multi storage consumer. Verified that the count of errors on both the clusters were the same

2022-01-26 18:22 UTC, nikhars commented on snuba/datasets/storages/errors_v2.py
> +    storage_set_key=StorageSetKey.ERRORS_V2,
This file is similar to https://github.com/getsentry/snuba/blob/master/snuba/datasets/storages/errors.py except for the storage keys over here and over here https://github.com/getsentry/snuba/pull/2349/files#diff-85d48fb2f4bfd3f7b16a317b13b37953c66c95ef61ff41544af53e23536f8178R26

2022-01-26 18:54 UTC, lynnagara commented
Is the new storage set intended to be temporary?

2022-01-26 23:08 UTC, nikhars commented
> Is the new storage set intended to be temporary?

Yes it would be temporary until we migrate completely to the new cluster.

2022-01-27 00:24 UTC, lynnagara commented
All storage sets need to be assigned to a cluster... unless you want to special case this and make it optional

2022-01-28 02:33 UTC, fpacifici commented
> All storage sets need to be assigned to a cluster... unless you want to special case this and make it optional

Not anymore. We had a deploy safety issue:
- The validation of settings, expected every storage set declared in the settings to be present in the code base
- This check expected that each declared storage set to be present in settings as assigned to a cluster.

https://github.com/getsentry/snuba/pull/2334/files#diff-7df145bde25ca970ceb9ba5c6fd95515b040310b905d4bfc9fc1e09b6e3eafa2L338-L341

This would make it impossible to deploy in prod where we cannot change settings and code atomically. 
Now we deploy the storage set in the code base first
And then we change the setting to assign the storage set to a cluster.

2022-01-28 17:19 UTC, fpacifici requested changes
Please fix the replacer state, otherwise it looks good.

2022-01-28 17:19 UTC, fpacifici commented on snuba/datasets/storages/errors_v2.py
> +        processor=ErrorsProcessor(promoted_tag_columns),
Please ensure that the processor itself does not mutate the original message. That would be a problem with the multi storage consumer as you saw for transactions.

2022-01-28 17:19 UTC, fpacifici commented on snuba/datasets/storages/errors_v2.py
> +        state_name=ReplacerState.ERRORS,
You need to provide a different value for this enum.
The ReplacerState is what we use in the replacements to separate the key space in redis between multiple replacers (we used it in the migration from events to errors).
So, in order to run two independent replacers you need two separate states here.

2022-01-28 18:14 UTC, lynnagara commented
Just to confirm do we really want to go down this route of duplicating the storage and filling them both just to do a ClickHouse upgrade? As opposed to just running the upgrade on the existing servers after testing it all in a staging environment

2022-01-28 19:02 UTC, fpacifici commented
This time yes. 
We need to upgrade in a timely manner because the version we have is out of support, then we will build what we need to test it in staging for the following upgrade

2022-02-11 20:14 UTC, merged