ref(snuba-admin): Add link to audit log
getsentry/snuba pull request #2477
Opened 2022-03-03 23:48 UTC by MeredithAnya

2022-03-03 23:56 UTC, lynnagara requested changes
The base URL should really be dynamic and not hardcoded to `snuba-admin.getsentry.net`

2022-03-22 17:31 UTC, onewland commented
> The base URL should really be dynamic and not hardcoded to `snuba-admin.getsentry.net`

Are you thinking base URL should be set in settings.py or something because I don't know how you'd determine this dynamically in a reasonable way?

I know this PR isn't super high priority but it's remained open for a long time and I'd like to see some of these stragglers get closed with either a merge or a wontfix

2022-03-22 17:31 UTC, onewland commented
> The base URL should really be dynamic and not hardcoded to `snuba-admin.getsentry.net`

Are you thinking base URL should be set in settings.py or something because I don't know how you'd determine this dynamically in a reasonable way?

I know this PR isn't super high priority but it's remained open for a long time and I'd like to see some of these stragglers get closed with either a merge or a wontfix

2022-03-22 17:55 UTC, lynnagara commented
Since we deploy the admin UI and API at the same URL I would be ok with pulling it from the request object. Open to alternative suggestions though.

2022-03-22 18:16 UTC, MeredithAnya commented
> Since we deploy the admin UI and API at the same URL I would be ok with pulling it from the request object. Open to alternative suggestions though.

Maybe this is the easiest way to start, I was just hoping there was a way we could instantiate the client with the url instead of passing it in every time we called `notify`.

2022-03-31 19:26 UTC, onewland commented
Looks good to me

2022-03-31 19:38 UTC, lynnagara commented on snuba/settings/__init__.py
> +ADMIN_URL = os.environ.get("ADMIN_URL", "http://localhost:1219")
Should we just make it `ADMIN_HOST + ADMIN_PORT` for the default settings?

2022-03-31 21:29 UTC, MeredithAnya commented on snuba/settings/__init__.py
> +ADMIN_URL = os.environ.get("ADMIN_URL", "http://localhost:1219")
I think I actually tried `0.0.0.0` and it looked wonky, I think admin web expects it to be `localhost`.

2022-03-31 21:35 UTC, onewland commented on snuba/settings/__init__.py
> +ADMIN_URL = os.environ.get("ADMIN_URL", "http://localhost:1219")
Yeah, 0.0.0.0 is a shorthand for TCP server socket listening that means "answer requests for any host", but it's not a meaningful IP address

2022-04-01 01:13 UTC, lynnagara approved these changes
Thanks

2022-04-01 17:39 UTC, merged