add link to clickhouse death queries page
getsentry/snuba pull request #2508
Opened 2022-03-14 20:08 UTC by volokluev

<img width="749" alt="image" src="https://user-images.githubusercontent.com/3169433/158252501-c1728b95-c7b3-4c97-b1de-885d5e9ef936.png">

Some queries can take down clickhouse. Put a warning and link to the notion page explaining what not to do. After this I will put this in the public docs so self-hosted users can use the admin tool without fear as well

2022-03-14 21:09 UTC, rahul-kumar-saini requested changes
Good idea 😄  self-hosted users should definitely be able to use the admin console

2022-03-14 21:09 UTC, rahul-kumar-saini commented on snuba/admin/static/tracing/index.tsx
> +        <a href="https://www.notion.so/sentry/Clickhouse-Death-Queries-d3873ff2f55e4b50b515926ba533f794">🛑 WARNING! BEFORE RUNNING QUERIES, READ THIS FIRST 🛑</a>
Wording nit

```suggestion
        <a href="https://www.notion.so/sentry/Clickhouse-Death-Queries-d3873ff2f55e4b50b515926ba533f794">🛑 WARNING! READ THIS BEFORE RUNNING QUERIES 🛑</a>
```
or
```suggestion
        <a href="https://www.notion.so/sentry/Clickhouse-Death-Queries-d3873ff2f55e4b50b515926ba533f794">🛑 WARNING! BEFORE RUNNING QUERIES, READ THIS 🛑</a>
```

2022-03-14 21:09 UTC, rahul-kumar-saini commented on snuba/admin/static/tracing/index.tsx
> +        <a href="https://www.notion.so/sentry/Clickhouse-Death-Queries-d3873ff2f55e4b50b515926ba533f794">🛑 WARNING! BEFORE RUNNING QUERIES, READ THIS FIRST 🛑</a>
I'm assuming the link would be updated to the live docs once #2509 is merged, so we could probably just wait till that is deployed and update the link within this PR.

2022-03-14 21:31 UTC, rahul-kumar-saini approved these changes

2022-03-15 18:20 UTC, evanh approved these changes

2022-03-15 18:57 UTC, merged