feat(profiling): Add index on profile_id
getsentry/snuba pull request #2633
Opened 2022-04-19 15:40 UTC by phacops

2022-07-07 22:59 UTC, fpacifici commented
@phacops  Could you please merge this ?

2022-09-20 23:30 UTC, lynnagara commented
@phacops What's the status of this migration? Do we need this index?

2022-09-21 00:50 UTC, lynnagara requested changes

2022-09-21 00:50 UTC, lynnagara commented on CODEOWNERS
> +/snuba/migrations/snuba_migrations/profiles @getsentry/profiling
Mind removing this line? The path has changed so it is causing a failure. Though it is our eventual goal that different teams will own separate paths within the Snuba repo we are not quite there yet.

2022-09-21 00:58 UTC, lynnagara commented on snuba/migrations/groups.py
> +        return ["0001_profiles", "0002_profiles_add_index_for_profile_id"]
Please rebase, and make this migration 0004 and 0002 exists now.

2022-09-21 16:32 UTC, lynnagara commented
This can't be merged currently since index on UUID is not supported in our minimum supported clickhouse version (20.3).

2022-09-21 16:32 UTC, closed without merging