Add replays-consumer to Freight
getsentry/snuba pull request #2839
Opened 2022-06-17 19:30 UTC by rgibert

Update Freight config to deploy to `replays-consumer`.

2022-06-17 19:40 UTC, lynnagara requested changes
We need to hold off as there is currently a bug in the schema causing all messages to fail processing

2022-06-24 00:05 UTC, fpacifici commented
@lynnagara  is this still the case ?

2022-07-06 07:32 UTC, fpacifici approved these changes

2022-07-28 18:38 UTC, rahul-kumar-saini commented
https://github.com/getsentry/snuba/pull/2997

2022-07-28 18:38 UTC, closed without merging