ci: Remove GCB tests and make GHA default for self-hosted e2e tests
getsentry/snuba pull request #3557
Opened 2022-12-22 22:41 UTC by ethanhs

This is the final step of [standardizing self-hosted e2e tests](https://github.com/getsentry/self-hosted/issues/1756). We remove tests from Google Cloud Build and replace it with the latest Github Action.

Note: this should not be merged until Tuesday

2022-12-27 18:29 UTC, hubertdeng123 requested changes
seeing `generic::invalid_argument: invalid build: invalid secrets: secretEnv "DOCKER_PASSWORD" is defined without being used` on the google cloud build

2022-12-27 18:38 UTC, ethanhs commented
> seeing generic::invalid_argument: invalid build: invalid secrets: secretEnv "DOCKER_PASSWORD" is defined without being used on the google cloud build

Should now be fixed!

2022-12-28 15:10 UTC, volokluev approved these changes

2022-12-28 18:15 UTC, hubertdeng123 approved these changes

2022-12-28 18:16 UTC, merged