ref: Remove more dead code
getsentry/snuba pull request #3935
Opened 2023-03-28 00:58 UTC by lynnagara

2023-03-28 13:52 UTC, evanh requested changes
There are people who still use the web dashboard for local development, I don't think we can just get rid of it without making sure that the admin tool supports their use cases.

2023-04-03 20:49 UTC, evanh commented on snuba/state/__init__.py
> -def get_concurrent(bucket: str) -> Any:
These functions are used by the web dashboard, I don't think you can just remove them.

2023-04-04 17:49 UTC, lynnagara commented
@evanh Not sure I understand the concern. Which features are these specifically? I really don't think we should keep supporting all this legacy code. Some of it like the way options are configure is wrong.

2023-04-04 19:52 UTC, evanh commented
> If people are incorrectly using this dashboard, can we please tell them to move to Snuba admin rather than keep this around.

I agree but I don't know how that dashboard is being used 100% and I don't think the admin tool covers the same use cases. For example the dashboard has a query tool that returns actual results and we don't allow that in the admin tool right now.

2023-04-04 20:22 UTC, evanh approved these changes
I missed the previous PR that removed the rest of the dashboard. Since it's already gone, I guess let's remove this and then hope no one wants us to add it back.

2023-04-04 20:46 UTC, merged