fix(clickhouse): Add a check for the max supported clickhouse version
getsentry/snuba pull request #4158
Opened 2023-05-10 19:28 UTC by davidtsuk

Closes SNS-1539

Add a check to ensure the clickhouse version is at most the max supported version.

2023-05-10 19:29 UTC, davidtsuk commented on snuba/migrations/clickhouse.py
> +CLICKHOUSE_SERVER_MAX_VERSION = "21.8"
Not sure if this needs to be 21.8.0.0 or if this works.

2023-05-11 18:01 UTC, nikhars requested changes
I would advise against blocking migrations altogether if the clickhouse version is higher than 21.8. Sentry and Snuba are both open source projects. While internally all our clickhouse clusters have a maximum version of 21.8, we do not know which version of clickhouse self hosted customers might be using. They could be on versions higher than 21.8. In those cases, migrations would start failing for them abruptly.

We should document what clickhouse versions we know work (happening in this [PR](https://github.com/getsentry/snuba/pull/4155) and leave it as is. Now it is upto self hosted customers to decide what to do with this information.

2023-05-12 17:57 UTC, davidtsuk commented
@nikhars Instead of blocking the migration, would it be better to just log a warning if they are on versions higher than 21.8?

2023-05-16 20:49 UTC, nikhars commented
> @nikhars Instead of blocking the migration, would it be better to just log a warning if they are on versions higher than 21.8?

Yes, logging a warning would be ok.

2023-05-18 19:21 UTC, rahul-kumar-saini approved these changes
Looks good pending @nikhars review

2023-05-18 19:21 UTC, rahul-kumar-saini commented on snuba/migrations/connect.py
> +            "Snuba has only been tested on Clickhouse versions up to {CLICKHOUSE_SERVER_MAX_VERSION} ({clickhouse.host}:{clickhouse.port} - {ver}). Higher versions might not be supported."
```suggestion
            f"Snuba has only been tested on Clickhouse versions up to {CLICKHOUSE_SERVER_MAX_VERSION} ({clickhouse.host}:{clickhouse.port} - {ver}). Higher versions might not be supported."
```

2023-05-18 20:44 UTC, nikhars commented
Were you able to test this in any way? If not, I would recommend that you test it out. You can do that by installing a clickhouse docker version locally by pulling it from https://hub.docker.com/r/clickhouse/clickhouse-server/ and testing against it

2023-05-19 15:29 UTC, davidtsuk commented
> Were you able to test this in any way? If not, I would recommend that you test it out. You can do that by installing a clickhouse docker version locally by pulling it from https://hub.docker.com/r/clickhouse/clickhouse-server/ and testing against it

```
snuba migrations list
2023-05-19 11:24:28,421 Initializing Snuba...
2023-05-19 11:24:29,673 Snuba initialization took 1.252941208s
2023-05-19 11:24:29,681 Snuba has only been tested on Clickhouse versions up to 21.8 (127.0.0.1:9000 - 23.4.2.11). Higher versions might not be supported.
system (readiness_state: complete)
[ ]  0001_migrations
...
```

2023-05-19 18:28 UTC, nikhars approved these changes

2023-05-23 15:09 UTC, merged