feat(search-issues): Add message column to search issues
getsentry/snuba pull request #4385
Opened 2023-06-20 23:13 UTC by wedamija

This adds the `message` column to search issues and starts writing to it. `message` is already being sent, but we missed including it a column initially.

I will let this write for a week or two before switching over to use it. We don't need the full 90 days of data for this to be effective.

2023-06-20 23:20 UTC, barkbarkimashark requested changes
Ahh, damn I missed this column ..

The code looks ok, but I think we'll need to split this PR up into two following steps:

1. PR1: Add the migration and include it in `group_loader.py` 
2. Merge PR1 and have someone from the SNS team manually run the migration against prod.
3. PR2: Start extracting the field in `search_issues_processor`, and exposing the field in the storage and entity.
4. Merge PR2 and deploy snuba.

2023-06-20 23:22 UTC, barkbarkimashark commented
For completeness, you probably also wanna add a processor and api test:
https://github.com/getsentry/snuba/blob/a882046c0b72f8f6b6748588498236e018a57b5b/tests/datasets/test_search_issues_processor.py#L429
https://github.com/getsentry/snuba/blob/173925bfe3318736ff0a45793e454ed724548689/tests/test_search_issues_api.py#L264

2023-06-21 20:28 UTC, barkbarkimashark approved these changes

2023-06-21 20:41 UTC, dbanda approved these changes

2023-06-21 20:43 UTC, merged