fix: fix 0001_functions and 0001_querylog for clickhouse 23
getsentry/snuba pull request #4842
Opened 2023-10-11 15:17 UTC by untitaker

2023-10-11 17:04 UTC, lynnagara requested changes
I don't think we can just change historical migrations otherwise new and older installations are out of sync. Don't we need a plan for existing users who have already run this?

2023-10-12 14:49 UTC, evanh commented
Is it possible to make this changes in a new migration? Or do we have to have these changes in from the beginning?

2023-10-18 15:12 UTC, evanh commented
> We need both a plan for users who have already run this (who migrate from an existing cluster) and for new clusters.

Is this plan laid out in a doc somewhere? It would be helpful I think to lay out the cases and come up with a plan for them.

2023-10-19 17:23 UTC, lynnagara approved these changes

2023-10-19 17:24 UTC, merged