fix(rust): Fix consumer deadlock on strategy panic
getsentry/snuba pull request #5216
Opened 2023-12-15 19:38 UTC by lynnagara

If strategy panics, we terminate the consumer now

2023-12-16 01:43 UTC, phacops approved these changes

2023-12-17 17:50 UTC, untitaker requested changes
this seems to work locally. can you:

* write some tests for this
* and apply the same fix for `submit()` and `join()` -- or ideally, catch all panics coming from `run_once`, in `run`?

2023-12-18 15:08 UTC, untitaker commented
@Swatinem i think there's a few unwraps in the python processor that can go off if subprocesses are being killed, but i think we generally should be resilient against this sort of crash because eventually arroyo should/will be used by third parties, with custom strategies + RunTask usage

2023-12-18 15:08 UTC, untitaker commented
I updated the PR body to link the JIRA ticket

2023-12-19 11:04 UTC, untitaker approved these changes

2023-12-19 18:00 UTC, merged