feat(errors) Remove clutter remaining from redis key migration
getsentry/snuba pull request #793
Opened 2020-02-24 21:09 UTC by fpacifici

https://github.com/getsentry/snuba/pull/781 left some migration clutter in the errors_replacer file in the code that generates the redis key to store groups that are pending replacement.
We added a string to identify which dataset the list of groups was belonging to. In order to ensure a safe migration we double wrote the keys in the old and new format.

Those old keys are not relevant anymore so this PR cleans up the clutter.

2020-02-24 22:30 UTC, tkaemming reviewed
Should there be some sort of data migration to perform this for on-premise/single tenant (since this can be done as a bunch of move/rename operations offline?)

2020-02-24 23:09 UTC, fpacifici commented
Damn, there is still one use case: if someone deploys #781 and this one together. 
Will leave this here for now and think how to do the migration.

2020-03-02 17:53 UTC, tkaemming requested changes
Marking this as changes requested based on earlier conversation (and to remove it from my review queue.)

2020-03-05 05:15 UTC, fpacifici commented
Sadly this is basically impossible until we have either a release model that defines how to deal with breaking change or a system to do data migrations. None of which will happen any time soon.

2020-03-05 05:15 UTC, closed without merging