fix(clickhouse): Improve handling of timezone-aware datetimes
getsentry/snuba pull request #818
Opened 2020-03-05 00:13 UTC by tkaemming

Following up on https://github.com/getsentry/snuba/pull/812#discussion_r388000053 to make datetime handling more robust if non-UTC timezones are returned. This also clarifies the date transformation behavior.

2020-03-05 00:30 UTC, fpacifici approved these changes

2020-03-05 00:30 UTC, fpacifici requested changes
sorry did not notice the test failure

2020-03-05 02:35 UTC, tkaemming commented
> sorry did not notice the test failure

This should be fixed now. Apparently `PST` was not available in the local timezone database and `tz.gettz` returned `None` rather than throwing an exception when the referenced timezone is not found, making `replace(tzinfo=tz.gettz('PST'))` effectively a noop.

2020-03-06 00:34 UTC, fpacifici approved these changes

2020-03-06 00:41 UTC, merged