ref(discover) Add an error_rate function
getsentry/snuba pull request #959
Opened 2020-05-20 21:20 UTC by evanh

2020-05-21 08:04 UTC, fpacifici requested changes

2020-05-21 08:04 UTC, fpacifici commented on snuba/util.py
> +        raise ValueError("Invalid format for error_rate()")
Same here, please use SPAN_STATUS_NAME_TO_CODE

2020-05-21 20:03 UTC, evanh commented on snuba/query/processors/error_rate_processor.py
> +            if isinstance(exp, FunctionCall) and exp.function_name == "error_rate":
Sorry what enum are you talking about? SPAN_STATUS_NAME_TO_CODE?

2020-05-22 21:44 UTC, fpacifici commented on snuba/query/processors/error_rate_processor.py
> +            if isinstance(exp, FunctionCall) and exp.function_name == "error_rate":
Yes, sorry it is not an enum. but that one.

2020-05-22 21:49 UTC, fpacifici approved these changes

2020-05-22 21:49 UTC, fpacifici commented on snuba/query/processors/error_rate_processor.py
> +                            "and",
you can use `binary_condition` also to build an AND.  And the function to use is declared in BooleanFunctions in the same place as ConditionFunctions

2020-05-25 17:31 UTC, evanh commented on snuba/query/processors/error_rate_processor.py
> +            if isinstance(exp, FunctionCall) and exp.function_name == "error_rate":
There's "unknown_error", which is code 2. And yes that is supposed to be considered a success. Or at least not a failure.

2020-05-27 18:51 UTC, merged